server:
  port: 8080

spring:
  application:
    name: archi-admin

  servlet:
    session:
      timeout: 30m
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: application-secret.yml
    activate:
      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true # SQL 로그 출력 여부

  ai:
    openai:
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.3
          max-tokens: 1000

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

  prometheus:
    metrics:
      export:
        enabled: true

app:
  upload-dir: uploads/