server:
  port: 8080

spring:
  application:
    name: archi-admin

  servlet:
    session:
      timeout: 30m
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: application-secret.yml
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://archi-mysql:3306/archi_db
    username: archi
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 생성 옵션 (none, validate, update, create, create-drop)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true # SQL 로그 출력 여부

app:
  upload-dir: uploads/